# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DIME' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  
  
  #pod 'Socket.IO-Client-Swift'
  
  # Pods for remoteios

  target 'DIMETests' do
    inherit! :search_paths  
    # Pods for testing
  end

  target 'DIMEUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  
end
